# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170704_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='author',
            new_name='builder',
        ),
        migrations.AddField(
            model_name='problem',
            name='actual_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='end_type',
            field=models.IntegerField(choices=[(1, b'Last hold is marked'), (2, b'Problem ends at top edge'), (3, b'Special ending - instructions on the wall')], default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 9, 20, 11, 13, 330687)),
        ),
        migrations.AddField(
            model_name='problem',
            name='grade',
            field=models.IntegerField(choices=[(1, b'Green'), (2, b'Blue'), (3, b'Red'), (4, b'Black'), (5, b'White'), (6, b'Grey')], default=2),
        ),
        migrations.AddField(
            model_name='problem',
            name='grip_color',
            field=models.CharField(default=b'color not defined', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='start_type',
            field=models.IntegerField(choices=[(1, b'Start has 2 holds'), (2, b'Start has 1 hold'), (3, b'Exceptional start - instructions on the wall')], default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.IntegerField(choices=[(1, b'Available'), (2, b'Under construction'), (3, b'Taken down')], default=1),
        ),
    ]
