# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170705_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_img',
            field=models.ImageField(blank=True, upload_to=b'img/problem_img/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 13, 16, 10, 53, 494733)),
        ),
    ]
